/*
 * Copyright (C) 2020 AriaLyy(https://github.com/AriaLyy/KeepassA)
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, you can obtain one at http://mozilla.org/MPL/2.0/.
 */
package com.lyy.demo

import android.os.Bundle
import android.util.Log
import android.view.View
import com.arialyy.frame.core.AbsActivity
import com.lyy.demo.databinding.ActivityExpendTextBinding

/**
 * @Author laoyuyu
 * @Description
 * @Date 2020/11/24
 **/
class ExpendTextViewActivity : AbsActivity<ActivityExpendTextBinding>() {
  val oneLineStr = "sdasd静坐之乐不一定非得去山中"

  val enStr = "In that code snippet there are somethings to be noticed:\n" +
      "*Now exists a class called ActivityMainBinding, which is autogenerated from the activity_main.xml and this contains all the references to use the views that the xml contains.\n" +
      "*The way of making an instance of ActivityMainBinding is a little variation of the way of setting the xml layout to an activity.\n" +
      "*There is also a new BR class which is some kind of secondary R class used to store the variables declared on the data tag of the xml.\n" +
      "*After setting the variable to the binding object, it is necessary to call the executePendingBindings() in order to set the user variable attributes to the marked views.\n" +
      "After compiling this you’ll be able to see that the Data has been set to your view without the necessity of writing any textView.text = user.name\n" +
      "This was my simple approach to use DataBinding inside a Kotlin project. I hope this is being useful to you."
  val zhStr = "古人说人生有八乐：“静坐、读书、赏花、玩月、观画、听鸟、狂歌、高卧。”清代医家石成金是养生高人，他总结出的“人生八乐”颇有些意趣，是为神仙之乐。\n" +
      "　　\n" +
      "　　静坐之乐不一定非得去山中，不一定非得到寺庙，只需寻得一处闲地，无人搅扰便好。松衣宽带，手拈串珠，心性内敛，不问流年，澄心静坐。收心敛性，静坐养心，那种好，只能意会，不能言传。\n" +
      "　　\n" +
      "　　读书之乐孤灯如豆，一卷在手，书香缱绻。有人说“腹有诗书气自华”，我却觉得倒不如“有书真富贵，无事小神仙”来得自在和无所求，在别人的故事里找寻自己的快乐，做逍遥游。\n" +
      "　　\n" +
      "　　赏花之乐古人风雅之事，赏花为其中之一。观其色，赏其姿，品其韵，闻其香，疏影斜横，暗香浮动。闲来无事，养花植草，涵养心性，在花花草草的世界里觅得片刻闲适，不是雅事一桩？\n" +
      "　　\n" +
      "　　玩月之乐“掬水月在手，弄花香满衣。”水中观月，林中觅月，屋中窥月，高台赏月，在清淡的月光里，神清气爽，骨清心明。明明是自己流连忘返，却偏偏要说“花常留我赏，月不放人眠”。\n" +
      "　　\n" +
      "　　观画之乐雅乐需要知音，观画亦是如此。線条、色彩、构图、纸张，方寸世界，别有洞天。画者独具匠心，释放激情，宣泄灵感；对于观者来说，则是一场视觉上的盛宴，精神上的享受。\n" +
      "　　\n" +
      "　　听鸟之乐有一种更加贴近大自然的音乐，那就是百鸟和鸣。清晨或黄昏，闲步公园、郊区，在林间漫步时，除了看花赏景，侧耳听一听鸟鸣，可以松弛一下绷紧的神经，“松阴张亭盖，鸟声奏管弦”。\n" +
      "　　\n" +
      "　　狂歌之乐醉舞狂歌，是一种状态，是一种气势，是一种宣泄，是一处极致的情感表达，既可以表达心中的欣喜之情，也可以解除心中郁闷之惑。无事登高，狂歌一曲，归来后，心中清宁。\n" +
      "　　\n" +
      "　　高卧之乐人生最悠闲的时光，莫过于高卧北窗，安然榻上。悠然地躺在床上，任光阴流淌，任世事浮沉，喧嚣有声。我自如闲云野鹤一般，管它今夕是何夕，高卧睡大觉，且把流年渡。\n" +
      "　　\n" +
      "　　人生有“八苦”，也有“八乐”，泾渭分明，苦乐交错。好在人生就是由苦和乐互相交错而成，没有苦，哪来的乐？苦和乐成为生活的重要组成部分，懂得“日日是好日，时时是好时”这个道理最重要。"

  val hh = "Animate 中的多语言文本\n" +
      "您可以用下列方式将多语言文本包含在文档中：\n" +
      "\n" +
      "（Animate 中已弃用）使用“字符串”面板，本地化人员可以在 Animate 中的中心位置编辑字符串，或者用其首选软件或翻译记忆库在外部 XML 文件中编辑字符串。Animate 支持在“字符串”面板和 XML 文件中使用多行字符串。\n" +
      "\n" +
      "您可以选择在应用程序中嵌入哪些字符集，您的选择将限制所发布的 SWF 文件中字型的数量并减小文件大小。\n" +
      "\n" +
      "用西式键盘在舞台上用中文、日文和韩文创建文本。\n" +
      "\n" +
      "如果您的系统装有 Unicode 字体，则可以在文本字段中直接输入文本。 因为字体不是嵌入的，所以您的用户也必须有 Unicode 字体。\n" +
      "\n" +
      "在 Animate 文档中包含多语言文本还有其他一些不常用的方法，包括以下几种：\n" +
      "\n" +
      "您可以用 #include 动作。\n" +
      "\n" +
      "通过使用 loadVariables 或 getURL 动作，或者 LoadVars 或 XML 对象，在运行时将外部文本或 XML 文件加载到 Animate 应用程序中。\n" +
      "\n" +
      "在动态或输入文本字段变量的字符串值中输入 Unicode 转义字符。\n" +
      "\n" +
      "在库中创建嵌入字体作为元件。\n" +
      "\n" +
      "要正确显示 Unicode 编码的文本，用户必须可以访问包含文本中所用字型（字符）的字体。\n" +
      "\n" +
      "有关多语言内容的范例，请参阅“Animate 范例”页，网址：www.adobe.com/go/learn_fl_samples_cn。下载并解压缩 Samples zip 文件，然后浏览到 Text\\MultilingualContent 文件夹以访问该范例。\n" +
      "\n" +
      "关于以 Unicode 编码的文本的字体\n" +
      "使用以 Unicode 编码的外部文件时，您的用户必须能访问包含文本文件中使用的所有字型的字体。 默认情况下，Animate 会存储动态或输入文本文件中使用的字体名称。在 SWF 文件播放期间，Flash Player 7（和更低版本）会在运行该播放器的操作系统中查找这些字体。\n" +
      "\n" +
      "如果 SWF 文件中的文本含有指定的字体不支持的字型，Flash Player 7 和 Flash Player 8 都会尝试在用户的系统中寻找支持这些字型的字体。 播放器并不是总能找到适合的字体。 此功能的行为取决于用户系统及运行 Flash Player 的操作系统中的可用字体。\n" +
      "\n" +
      "XML 字体嵌入表\n" +
      "当您选择要在 FLA 文件中嵌入的字体范围时，Animate 使用 UnicodeTable.xml 文件确定要嵌入的字符。UnicodeTable.xml 文件包含各种语言所需的字符范围，它驻留在计算机的用户配置文件夹中。该文件位于下列目录中：\n" +
      "\n" +
      "Windows：<引导驱动器>\\Documents and Settings\\<用户>\\Local Settings\\Application Data\\Adobe\\Flash<版本>\\<语言>\\Configuration\\FontEmbedding\\\n" +
      "\n" +
      "Macintosh：<用户>/Library/Application Support/Adobe/Flash <版本>/<语言>/Configuration/FontEmbedding/\n" +
      "\n" +
      "字体集组合的基础是 Unicode 协会定义的 Unicode 块。 为提供更加简单的工作流程，在您选择某种特定语言时，所有相关的字型范围均被嵌入，即使它们散布于不连续的组合中。\n" +
      "\n" +
      "例如，如果您选择“韩文”，则会嵌入以下 Unicode 字符范围：\n" +
      "\n" +
      "3131-318E Hangul 符号\n" +
      "\n" +
      "3200-321C Hangul 特殊字符\n" +
      "\n" +
      "3260-327B Hangul 特殊字符\n" +
      "\n" +
      "327F-327F 韩文符号\n" +
      "\n" +
      "AC00-D7A3 Hangul 符号\n" +
      "\n" +
      "如果您选择“韩文 + CJK”，则会嵌入更大的字体集：\n" +
      "\n" +
      "3131-318E Hangul 符号\n" +
      "\n" +
      "3200-321C Hangul 特殊字符\n" +
      "\n" +
      "3260-327B Hangul 特殊字符\n" +
      "\n" +
      "327F-327F 韩文符号\n" +
      "\n" +
      "4E00-9FA5 CJK 符号\n" +
      "\n" +
      "AC00-D7A3 Hangul 符号\n" +
      "\n" +
      "F900-FA2D CJK 符号\n" +
      "\n" +
      "有关不同编写系统的特定 Unicode 范围的详细信息，请参阅 Unicode 5.2.0 规范。\n" +
      "\n" +
      "下表提供了有关嵌入字体集的更多详细信息：\n" +
      "\n" +
      "范围\n" +
      "\n" +
      "描述\n" +
      "\n" +
      "大写 [A-Z]\n" +
      "\n" +
      "基本拉丁语大写字型，以及空格字符 0x0020。\n" +
      "\n" +
      "小写 [a-z]\n" +
      "\n" +
      "基本拉丁语小写字型，以及空格字符 0x0020。\n" +
      "\n" +
      "数字 [0-9]\n" +
      "\n" +
      "基本拉丁语数字字型\n" +
      "\n" +
      "标点符号 [!@#%...]\n" +
      "\n" +
      "基本拉丁语标点\n" +
      "\n" +
      "基本拉丁语\n" +
      "\n" +
      "Unicode 范围 0x0020 至 0x007E 内的基本拉丁语字型。\n" +
      "\n" +
      "日语假名\n" +
      "\n" +
      "平假名和片假名字型（包括半角格式）\n" +
      "\n" +
      "日语汉字 – 第 1 级\n" +
      "\n" +
      "日语汉字字符\n" +
      "\n" +
      "日语（全部）\n" +
      "\n" +
      "日语假名和汉字（包括标点和特殊字符）\n" +
      "\n" +
      "基本 Hangul\n" +
      "\n" +
      "最常用的韩文字符、罗马字符、标点和特殊字符/符号\n" +
      "\n" +
      "Hangul（全部）\n" +
      "\n" +
      "11,720 个韩文字符（按 Hangul 音节排序）、罗马字符、标点和特殊字符/符号\n" +
      "\n" +
      "繁体中文 – 第 1 级\n" +
      "\n" +
      "中国台湾地区最常用的 5000 个繁体中文字符\n" +
      "\n" +
      "繁体中文（全部）\n" +
      "\n" +
      "中国台湾地区和中国香港特别行政区使用的所有繁体中文字符和标点\n" +
      "\n" +
      "简体中文 – 第 1 级\n" +
      "\n" +
      "中国大陆最常用的 6000 个简体中文字符和标点\n" +
      "\n" +
      "中文（全部）\n" +
      "\n" +
      "所有繁体和简体中文字符与标点\n" +
      "\n" +
      "泰语\n" +
      "\n" +
      "所有泰语字型\n" +
      "\n" +
      "梵文\n" +
      "\n" +
      "所有梵文字型\n" +
      "\n" +
      "拉丁语 I\n" +
      "\n" +
      "拉丁语 1 补充，范围 0x00A1 至 0x00FF（包括标点、上标和下标、货币符号和类似于字母类的符号）\n" +
      "\n" +
      "拉丁语扩展 A\n" +
      "\n" +
      "拉丁"

  override fun initData(savedInstanceState: Bundle?) {
    super.initData(savedInstanceState)
    binding.etv.maxLines = 6
    binding.etv.setHasAnimation(true)
    binding.etv.setExpandSuffix("展开")
    binding.etv.setShrinkSuffix("收起")
    binding.etv.setOnClickListener {
      Log.d(TAG, "文本被点击")
    }
  }

  override fun setLayoutId(): Int {
    return R.layout.activity_expend_text
  }

  fun onClick(v: View) {
    when (v.id) {
      R.id.btnEn -> {
        binding.etv.originalText = enStr
      }
      R.id.btnZh -> {
        binding.etv.originalText = zhStr
      }
      R.id.btnMulti -> {
        binding.etv.originalText = hh
      }
      R.id.btnGetText ->{
        Log.d(TAG, binding.etv.originalText.toString())
      }
    }
  }
}